apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "deploymentName" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
        version: {{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
          - name: ELASTIC_APM_SERVER_URL
            value: "{{ .Values.apmServerUrl }}"
          - name: USER_SERVER_URL
            value: "{{ .Values.userServerUrl }}"
          - name: KAFKA_BROKER_URL
            value: "{{ .Values.kafkaBrokerUrl }}"
          - name: SQL_DRIVER_NAME
            valueFrom:
              configMapKeyRef:
                name: user-db-config
                key: driverName
          - name: SQL_DATA_SOURCE_NAME
            valueFrom:
              configMapKeyRef:
                name: user-db-config
                key: productDSN
        resources:
{{ toYaml .Values.resources | indent 12 }}
